"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const vm = require("node:vm");
const path = require("node:path");
const context = { console, window: { dispatchEvent() {} }, CustomEvent: class {} };
vm.createContext(context);
vm.runInContext(fs.readFileSync(path.join(__dirname, "../v2-systems.js"), "utf8"), context);
const s = context.StellarV2Systems;
const now = Date.UTC(2026, 8, 17, 8);
let checks = 0;
function check(value, expected) { assert.equal(value, expected); checks++; }
const game = { lifetimeDust: 1e8, endgame: { companions: ["dustMoth"] }, expedition: { supplies: 10 } };
const v = s.freshState(now);
check(s.chooseOrder(v, "expand", now), false);
s.selectDaily(v, game, "industry", now);
check(s.chooseOrder(v, "expand", now), true);
check(s.chooseOrder(v, "process", now), false);
check(s.claimOrder(v), null);
s.recordMetric(v, "unitsBought", 5, game, now);
check(s.claimOrder(v).materials.alloy, 3);
check(s.claimOrder(v), null);
check(s.chooseOrder(v, "process", now + 86400000), true);
s.recordMetric(v, "operationsCompleted", 2, game, now + 86400000);
check(s.claimOrder(v).tokens, 8);
for (let i = 0; i < 8; i++) {
  check(s.claimEcho(v), null);
  s.recordMetric(v, "expeditionRoutes", 1, game, now);
  check(v.echo.stage, 1);
  check(s.interpretEcho(v, { endgame: { companions: [] } }), false);
  check(s.interpretEcho(v, game), true);
  s.recordMetric(v, "operationsCompleted", 1, game, now);
  check(s.claimEcho(v).tokens, 10);
  check(v.echo.completed, i + 1);
}
check(s.claimEcho(v), null);
check(s.startReturnPlan(v, game, "night", now), true);
check(game.expedition.supplies, 7);
check(s.startReturnPlan(v, game, "short", now), false);
check(s.claimReturnPlan(v, now + 3600000), null);
check(s.claimReturnPlan(v, now + 8 * 3600000).tokens, 12);
check(s.claimReturnPlan(v, now + 8 * 3600000), null);
check(s.startReturnPlan(v, game, "short", now + 8 * 3600000), false);
const migrated = s.sanitize(JSON.parse(JSON.stringify(v)), now);
check(migrated.echo.completed, 8);
check(migrated.returnPlan.claimed, true);
check(migrated.order.claimed, true);
check(s.sanitize({}).returnPlan.id, "");
check(s.sanitize({ echo: { completed: 99, archive: ["bogus"] } }).echo.completed, 0);
console.log(`linked journey ok: ${checks} assertions; orders, eight collections, time gates, duplicate claims, migration`);
