/* Shared by the browser and the deterministic balance simulation. */
(function (root, factory) {
  const data = factory();
  if (typeof module === "object" && module.exports) module.exports = data;
  else root.SalvageData = data;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";
  return Object.freeze({
    VERSION: 32,
    GAME_VERSION: "3.2.0-preview.2",
    PRESTIGE_DUST: 30000000,
    OFFLINE_SECONDS: 8 * 3600,
    MAX_NUMBER: 1e100,
    BUILDINGS: [
      {
        id: "drone",
        name: "拾荒无人机",
        cost: 12,
        growth: 1.16,
        rate: 0.8,
        unlock: 0,
        detail: "把漂浮残骸带回航站。",
      },
      {
        id: "sail",
        name: "光帆采集器",
        cost: 100,
        growth: 1.17,
        rate: 4,
        unlock: 150,
        detail: "展开光帆，接住恒星散落的能量。",
      },
      {
        id: "forge",
        name: "轨道熔铸站",
        cost: 1500,
        growth: 1.19,
        rate: 30,
        unlock: 1500,
        detail: "让废弃金属重新成为舰体。",
      },
      {
        id: "relay",
        name: "深空中继环",
        cost: 20000,
        growth: 1.2,
        rate: 180,
        unlock: 15000,
        detail: "把整条航线连成一张回收网络。",
      },
    ],
    MILESTONES: [10, 25, 50],
    MODULE_MAX_LEVEL: 3,
    MODULE_UPGRADE_SAMPLES: [6, 12],
    ROUTES: [
      {
        id: "industry",
        name: "工业航线",
        subtitle: "让舰队彼此成就",
        detail:
          "无人机每达 10 艘，全舰队产量 +8%（最多 +40%）；设施达到 25 艘时额外产量 ×1.25。适合长时间离线。",
      },
      {
        id: "reclaim",
        name: "回收航线",
        subtitle: "抓住每一次短暂信号",
        detail:
          "扫描收益 ×3；金色信标奖励 ×2，并触发 20 秒双倍生产。扫描随舰队产量成长，适合短时主动游玩。",
      },
      {
        id: "explore",
        name: "探索航线",
        subtitle: "用今天的产量换明天的发现",
        detail:
          "探索时间缩短 35%，产量分流减半；每次探索多带回 1 份样本，风险探索成功率提升至 80%。",
      },
    ],
    RESEARCH: [
      {
        id: "laser",
        name: "聚焦扫描",
        cost: 40,
        unlock: 40,
        detail: "扫描基础收益 ×2。",
      },
      {
        id: "panels",
        name: "光电接续",
        cost: 120,
        unlock: 120,
        detail: "全舰队产量 ×1.2。",
      },
      {
        id: "compact",
        name: "模块化装配",
        cost: 600,
        unlock: 600,
        detail: "所有建筑费用降低 10%。",
      },
      {
        id: "navigation",
        name: "回声导航",
        cost: 900,
        unlock: 600,
        detail: "风险探索成功率 +5%，解锁失落温室航线。",
      },
      {
        id: "network",
        name: "协同网络",
        cost: 2400,
        unlock: 2400,
        detail: "全舰队产量 ×1.35。",
      },
    ],
    MODULES: [
      {
        id: "battery",
        name: "储能矩阵",
        samples: 4,
        detail: "每级全舰队产量 +12%。",
      },
      {
        id: "scanner",
        name: "残骸透镜",
        samples: 4,
        detail: "每级扫描与信标收益 +25%。",
      },
      {
        id: "medbay",
        name: "医疗舱电源",
        samples: 4,
        story: "hospital",
        detail: "每级全舰队产量 +10%。来自废弃医院船。",
      },
      {
        id: "nav",
        name: "惯性导航仪",
        samples: 6,
        detail: "每级探索时间缩短 10%。",
      },
      {
        id: "solar",
        name: "温室集光阵",
        samples: 6,
        story: "garden",
        detail: "每级光帆采集器产量 +30%。来自失落温室。",
      },
    ],
    MISSIONS: [
      {
        id: "wreck",
        name: "废弃医院船",
        seconds: 90,
        diversion: 0.2,
        yieldSeconds: 50,
        samples: 1,
        chance: 1,
        story: "hospital",
        unlockPort: 0,
        detail: "安全探索。船上仍有一个微弱的求救信号。",
      },
      {
        id: "belt",
        name: "寂静残骸带",
        seconds: 120,
        diversion: 0.2,
        yieldSeconds: 75,
        samples: 2,
        chance: 1,
        unlockPort: 0,
        detail: "安全探索。稳定回收星尘和修复航站所需的样本。",
      },
      {
        id: "echo",
        name: "裂隙回声",
        seconds: 150,
        diversion: 0.4,
        yieldSeconds: 150,
        samples: 3,
        chance: 0.65,
        unlockPort: 0,
        detail:
          "自愿风险探索。失败只损失分流时间，仍带回 1 份样本；成功可发现舰装。",
      },
      {
        id: "garden",
        name: "失落温室",
        seconds: 180,
        diversion: 0.25,
        yieldSeconds: 110,
        samples: 3,
        chance: 1,
        story: "garden",
        unlockPort: 1,
        research: "navigation",
        detail: "安全探索。没有人的温室里，仍有一株植物在等待日出。",
      },
      {
        id: "message",
        name: "漂泊通信带",
        seconds: 150,
        diversion: 0.2,
        yieldSeconds: 150,
        samples: 4,
        chance: 1,
        story: "relay",
        unlockPort: 3,
        chapter: true,
        requiresStory: "hospital",
        detail: "安全探索。沿着医院船留下的编号，寻找那份讯息的回执。",
      },
      {
        id: "seedbank",
        name: "失重种子库",
        seconds: 210,
        diversion: 0.25,
        yieldSeconds: 160,
        samples: 6,
        chance: 1,
        story: "nursery",
        unlockPort: 3,
        chapter: true,
        project: "relay",
        requiresStory: "garden",
        equipment: { id: "nav", level: 2 },
        detail: "安全探索。装备 2 级惯性导航仪，穿过缓慢旋转的育种舱。",
      },
      {
        id: "horizon",
        name: "黎明边界",
        seconds: 240,
        diversion: 0.3,
        yieldSeconds: 200,
        samples: 8,
        chance: 1,
        story: "horizon",
        unlockPort: 3,
        chapter: true,
        project: "nursery",
        research: "navigation",
        equipment: { id: "scanner", level: 2 },
        detail: "安全探索。装备 2 级残骸透镜，从恒星噪声里辨认另一座航站。",
      },
    ],
    STORIES: {
      hospital: {
        title: "最后一盏手术灯",
        text: "医院船里没有幸存者。但手术灯仍在亮着，备用电源护着一份没有发出的平安讯息。你准备带回什么？",
        choices: [
          {
            id: "scrap",
            name: "拆解船体",
            detail: "立即获得 60 秒产量的星尘。",
            dustSeconds: 60,
          },
          {
            id: "repair",
            name: "修复备用电源",
            detail: "获得永久舰装「医疗舱电源」，装备后产量 +10%。",
            module: "medbay",
          },
          {
            id: "preserve",
            name: "保留那份讯息",
            detail: "记录故事，并带回额外 3 份航站样本。",
            samples: 3,
          },
        ],
      },
      garden: {
        title: "等不到的日出",
        text: "温室的日历停在很久以前。最后一页写着：如果有人读到这里，请替我们给这株幼苗一次日出。",
        choices: [
          {
            id: "scrap",
            name: "回收光照设备",
            detail: "立即获得 90 秒产量的星尘。",
            dustSeconds: 90,
          },
          {
            id: "repair",
            name: "重新点亮温室",
            detail: "获得永久舰装「温室集光阵」，光帆产量 +30%。",
            module: "solar",
          },
          {
            id: "preserve",
            name: "带着幼苗启航",
            detail: "记录故事，并带回额外 5 份航站样本。",
            samples: 5,
          },
        ],
      },
      relay: {
        title: "终于收到的回信",
        continuity: {
          story: "hospital",
          choices: {
            scrap:
              "当年拆解医院船时登记的船体编号，替你在漂泊中继中找到了同一条航线。那些金属没有白白离开。",
            repair:
              "修复过的备用电源播出完整离港日志，你沿着其中的通信频段，找到了漂泊中继。那盏灯一直指着这里。",
            preserve:
              "你保存的平安讯息里藏着一个回执地址。如今，星港终于有能力把它送往该去的地方。",
          },
        },
        text: "迟到的回执从远方传来：『这里是灯塔九号。我母亲在那艘船上。谢谢你告诉我她最后做了什么。』回信者阿遥并不要求奇迹，只问这条航线能否再次通行。你准备怎样连接两地？",
        choices: [
          {
            id: "public",
            name: "共享中继频段",
            detail: "带回额外 6 份样本，供两地建设。",
            samples: 6,
          },
          {
            id: "power",
            name: "为通信阵列供电",
            detail: "获得储能矩阵或升 1 级；满 3 级时改为 6 份样本。",
            module: "battery",
            overflowSamples: 6,
          },
          {
            id: "salvage",
            name: "回收废弃中继外壳",
            detail: "获得 120 秒产量的星尘，保留通信核心。",
            dustSeconds: 120,
          },
        ],
      },
      nursery: {
        title: "不只是一株幼苗",
        continuity: {
          story: "garden",
          choices: {
            scrap:
              "回收光照设备时留下的序号，对应着种子库的培育清单。设备离开了旧温室，里面的记录却替更多种子找到了家。",
            repair:
              "重新点亮的温室送来一份发芽记录。失重种子库据此确认：这条航线还有人照顾生命。",
            preserve:
              "你带走的幼苗已经长出新叶。叶片的纹路与种子库的标本一致，它曾经属于一整座尚未醒来的花园。",
          },
        },
        text: "库门后不是燃料，而是数千个休眠的种子盒。园艺员苇的录音说：『别把我的名字刻在墙上。种下它们，等别人来坐一坐。』阿遥发来消息，她的航站能出人手，却缺少可种植的土地。你选择先带回什么？",
        choices: [
          {
            id: "seeds",
            name: "带回种子与培育记录",
            detail: "带回额外 8 份样本，准备永久育种舱。",
            samples: 8,
          },
          {
            id: "light",
            name: "接续旧库的光照阵列",
            detail: "获得温室集光阵或升 1 级；满 3 级时改为 8 份样本。",
            module: "solar",
            overflowSamples: 8,
          },
          {
            id: "tools",
            name: "回收闲置培育机械",
            detail: "获得 150 秒产量的星尘，种子留在恒温箱中。",
            dustSeconds: 150,
          },
        ],
      },
      horizon: {
        title: "有人点亮另一端",
        text: "黎明边界没有宝藏船，只有一座靠轮流停机维持的航站。阿遥站在观测窗前：『你不是来取走最后一点东西的，对吗？』你把星港、种子库和中继的坐标交给她。第一次，屏幕上的航线不再以残骸为终点。远航灯塔需要一份启用宣言。",
        choices: [
          {
            id: "welcome",
            name: "先向漂泊者发出邀请",
            detail: "带回额外 10 份样本，为接待来船做准备。",
            samples: 10,
          },
          {
            id: "archive",
            name: "先校验每一段安全航线",
            detail: "获得惯性导航仪或升 1 级；满 3 级时改为 6 份样本。",
            module: "nav",
            overflowSamples: 6,
          },
          {
            id: "supply",
            name: "先送出一批建设物资",
            detail: "获得 180 秒产量的星尘，完成两地共同回收。",
            dustSeconds: 180,
          },
        ],
      },
    },
    PROJECTS: [
      {
        id: "relay",
        name: "共鸣中继",
        mission: "message",
        story: "relay",
        cores: 2,
        samples: 10,
        detail: "永久全舰队产量 ×1.05；开放失重种子库。",
        text: "共鸣中继接通。阿遥的声音第一次不再隔着长久的静电：『收到，归航星港。』",
      },
      {
        id: "nursery",
        name: "永久育种舱",
        mission: "seedbank",
        story: "nursery",
        cores: 3,
        samples: 14,
        detail: "每次成功探索永久多带回 1 份样本；开放黎明边界。",
        text: "第一批种子在育种舱里苏醒。这里开始生产的，除了星尘，还有下一个春天。",
      },
      {
        id: "lighthouse",
        name: "远航灯塔",
        mission: "horizon",
        story: "horizon",
        cores: 4,
        samples: 20,
        detail: "所有探索时间永久缩短 10%；第二章完成。",
        text: "远航灯塔亮起，另一端也传来回应。那些曾只属于一个人的归航坐标，成为了两座航站之间的路。第二章「远航星图」完成。",
      },
    ],
    PORT: [
      {
        name: "重新点亮通信塔",
        cores: 2,
        samples: 4,
        text: "第一束光离开了寂静航站。远处传来温室的坐标：航线还没有结束。",
      },
      {
        name: "修复跃迁泊位",
        cores: 5,
        samples: 8,
        text: "旧泊位接上了新的电源。船不再只是路过，这里终于可以成为归航的地方。",
      },
      {
        name: "建成归航星港",
        cores: 9,
        samples: 12,
        text: "最后一盏灯亮起。医院船的讯息、温室的幼苗和拾荒者们，都有了回来的地址。",
      },
    ],
    CAPABILITIES: [
      {
        run: 1,
        id: "autoBuy",
        name: "自动购买",
        detail: "每秒按产量回本时间购买，首艘无人机随新航次启航。",
      },
      {
        run: 2,
        id: "planning",
        name: "预算与优先级",
        detail: "可设置保留星尘，并选择均衡、里程碑或高级设施优先。",
      },
      {
        run: 3,
        id: "autoResearch",
        name: "自动研究",
        detail: "每 5 秒研究一项可负担科技，同样遵守预算。",
      },
      {
        run: 4,
        id: "autoDispatch",
        name: "重复派遣",
        detail: "自动收取普通报告并继续安全探索，故事选择由你处理。",
      },
    ],
  });
});
