/* Shared by the browser and the deterministic balance simulation. */
(function (root, factory) {
  const data = factory();
  if (typeof module === "object" && module.exports) module.exports = data;
  else root.SalvageData = data;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";
  const data = {
    VERSION: 32,
    GAME_VERSION: "3.4.0-preview.1",
    PRESTIGE_DUST: 30000000,
    OFFLINE_SECONDS: 8 * 3600,
    MAX_NUMBER: 1e100,
    BUILDINGS: [
      {
        id: "drone",
        name: "拾荒无人机",
        cost: 12,
        growth: 1.16,
        rate: 0.8,
        unlock: 0,
        detail: "把漂浮残骸带回航站。",
      },
      {
        id: "sail",
        name: "光帆采集器",
        cost: 100,
        growth: 1.17,
        rate: 4,
        unlock: 150,
        detail: "展开光帆，接住恒星散落的能量。",
      },
      {
        id: "forge",
        name: "轨道熔铸站",
        cost: 1500,
        growth: 1.19,
        rate: 30,
        unlock: 1500,
        detail: "让废弃金属重新成为舰体。",
      },
      {
        id: "relay",
        name: "深空中继环",
        cost: 20000,
        growth: 1.2,
        rate: 180,
        unlock: 15000,
        detail: "把整条航线连成一张回收网络。",
      },
    ],
    MILESTONES: [10, 25, 50],
    MODULE_MAX_LEVEL: 3,
    MODULE_UPGRADE_SAMPLES: [6, 12],
    ROUTES: [
      {
        id: "industry",
        name: "工业航线",
        subtitle: "让舰队彼此成就",
        detail:
          "无人机每达 10 艘，全舰队产量 +8%（最多 +40%）；设施达到 25 艘时额外产量 ×1.25。适合长时间离线。",
      },
      {
        id: "reclaim",
        name: "回收航线",
        subtitle: "抓住每一次短暂信号",
        detail:
          "扫描收益 ×3；金色信标奖励 ×2，并触发 20 秒双倍生产。扫描随舰队产量成长，适合短时主动游玩。",
      },
      {
        id: "explore",
        name: "探索航线",
        subtitle: "用今天的产量换明天的发现",
        detail:
          "探索时间缩短 35%，产量分流减半；每次探索多带回 1 份样本，风险探索成功率提升至 80%。",
      },
    ],
    RESEARCH: [
      {
        id: "laser",
        name: "聚焦扫描",
        cost: 40,
        unlock: 40,
        detail: "扫描基础收益 ×2。",
      },
      {
        id: "panels",
        name: "光电接续",
        cost: 120,
        unlock: 120,
        detail: "全舰队产量 ×1.2。",
      },
      {
        id: "compact",
        name: "模块化装配",
        cost: 600,
        unlock: 600,
        detail: "所有建筑费用降低 10%。",
      },
      {
        id: "navigation",
        name: "回声导航",
        cost: 900,
        unlock: 600,
        detail: "风险探索成功率 +5%，解锁失落温室航线。",
      },
      {
        id: "network",
        name: "协同网络",
        cost: 2400,
        unlock: 2400,
        detail: "全舰队产量 ×1.35。",
      },
    ],
    MODULES: [
      {
        id: "battery",
        name: "储能矩阵",
        samples: 4,
        detail: "每级全舰队产量 +12%。",
      },
      {
        id: "scanner",
        name: "残骸透镜",
        samples: 4,
        detail: "每级扫描与信标收益 +25%。",
      },
      {
        id: "medbay",
        name: "医疗舱电源",
        samples: 4,
        story: "hospital",
        detail: "每级全舰队产量 +10%。来自废弃医院船。",
      },
      {
        id: "nav",
        name: "惯性导航仪",
        samples: 6,
        detail: "每级探索时间缩短 10%。",
      },
      {
        id: "solar",
        name: "温室集光阵",
        samples: 6,
        story: "garden",
        detail: "每级光帆采集器产量 +30%。来自失落温室。",
      },
    ],
    MISSIONS: [
      {
        id: "wreck",
        name: "废弃医院船",
        seconds: 90,
        diversion: 0.2,
        yieldSeconds: 50,
        samples: 1,
        chance: 1,
        story: "hospital",
        unlockPort: 0,
        detail: "安全探索。船上仍有一个微弱的求救信号。",
      },
      {
        id: "belt",
        name: "寂静残骸带",
        seconds: 120,
        diversion: 0.2,
        yieldSeconds: 75,
        samples: 2,
        chance: 1,
        unlockPort: 0,
        detail: "安全探索。稳定回收星尘和修复航站所需的样本。",
      },
      {
        id: "echo",
        name: "裂隙回声",
        seconds: 150,
        diversion: 0.4,
        yieldSeconds: 150,
        samples: 3,
        chance: 0.65,
        unlockPort: 0,
        detail:
          "自愿风险探索。失败只损失分流时间，仍带回 1 份样本；成功可发现舰装。",
      },
      {
        id: "garden",
        name: "失落温室",
        seconds: 180,
        diversion: 0.25,
        yieldSeconds: 110,
        samples: 3,
        chance: 1,
        story: "garden",
        unlockPort: 1,
        research: "navigation",
        detail: "安全探索。没有人的温室里，仍有一株植物在等待日出。",
      },
      {
        id: "message",
        name: "漂泊通信带",
        seconds: 150,
        diversion: 0.2,
        yieldSeconds: 150,
        samples: 4,
        chance: 1,
        story: "relay",
        unlockPort: 3,
        chapter: true,
        requiresStory: "hospital",
        detail: "安全探索。沿着医院船留下的编号，寻找那份讯息的回执。",
      },
      {
        id: "seedbank",
        name: "失重种子库",
        seconds: 210,
        diversion: 0.25,
        yieldSeconds: 160,
        samples: 6,
        chance: 1,
        story: "nursery",
        unlockPort: 3,
        chapter: true,
        project: "relay",
        requiresStory: "garden",
        equipment: { id: "nav", level: 2 },
        detail: "安全探索。装备 2 级惯性导航仪，穿过缓慢旋转的育种舱。",
      },
      {
        id: "horizon",
        name: "黎明边界",
        seconds: 240,
        diversion: 0.3,
        yieldSeconds: 200,
        samples: 8,
        chance: 1,
        story: "horizon",
        unlockPort: 3,
        chapter: true,
        project: "nursery",
        research: "navigation",
        equipment: { id: "scanner", level: 2 },
        detail: "安全探索。装备 2 级残骸透镜，从恒星噪声里辨认另一座航站。",
      },
      {
        id: "white-noise",
        name: "白噪声海观测",
        seconds: 240,
        diversion: 0.3,
        yieldSeconds: 180,
        samples: 8,
        chance: 1,
        story: "observations",
        unlockPort: 3,
        campaign: true,
        project: "lighthouse",
        research: "navigation",
        equipment: { id: "scanner", level: 2 },
        detail: "让无人探针短程往返，核对导航仪与中继互相矛盾的坐标。",
      },
      {
        id: "false-beacon",
        name: "失准信标核验",
        seconds: 270,
        diversion: 0.3,
        yieldSeconds: 210,
        samples: 10,
        chance: 1,
        story: "beacon",
        unlockPort: 3,
        campaign: true,
        project: "lighthouse",
        requiresStory: "observations",
        equipment: { id: "nav", level: 2 },
        detail: "旧信标仍在广播错误坐标。核验它，同时寻找求助频道的声音。",
      },
      {
        id: "first-convoy",
        name: "第一支船队交接",
        seconds: 300,
        diversion: 0.35,
        yieldSeconds: 240,
        samples: 12,
        chance: 1,
        story: "arrival",
        unlockPort: 3,
        campaign: true,
        project: "lighthouse",
        requiresStory: "beacon",
        detail: "只走已经验证的短航段，为等待的船队逐段交接，带他们安全入港。",
      },
      {
        id: "supply-run",
        name: "两港补给线",
        seconds: 180,
        diversion: 0.2,
        yieldSeconds: 130,
        samples: 4,
        chance: 1,
        unlockPort: 3,
        requiresStory: "arrival",
        detail:
          "第一支船队留下了可复用的航路记录。往返两港，稳定回收物资与样本。",
      },
    ],
    PORT_FOCUSES: [
      {
        id: "reception",
        name: "接待扩容",
        samples: 18,
        diversion: 0.85,
        seconds: 1,
        bonusSamples: 0,
        detail:
          "建成备用泊位与轮班宿舍。第四章及后续救援航程分流减少 15%，为在港居民保留更多生产能力。",
        text: "祁岳把铺位、供暖和接班人逐项登记。备用泊位亮起接待灯，承诺有了可以核查的容量。",
      },
      {
        id: "ecology",
        name: "生态补给",
        samples: 18,
        diversion: 1,
        seconds: 1,
        bonusSamples: 2,
        detail:
          "建成育种补给站。第四章及后续救援每次成功归航额外带回 2 份样本，支持持续供给。",
        text: "两港居民在育种舱划出补给区，保留植物休息的光照时段。新来船上的园艺工接过培育表。",
      },
      {
        id: "archive",
        name: "档案校准",
        samples: 18,
        diversion: 1,
        seconds: 0.85,
        bonusSamples: 0,
        detail:
          "建成独立观测档案台。第四章及后续救援航程缩短 15%，让核验过的数据能够重复使用。",
        text: "归航保存原始观测与两港的签名副本。每段航路都标明来源、等待位置和暂停条件。",
      },
    ],
    LOADOUTS: [
      { id: "production", name: "日常生产" },
      { id: "voyage", name: "远航准备" },
    ],
    COUNCIL_MISSIONS: [
      {
        id: "port-council",
        name: "双港会议与离港日志",
        seconds: 150,
        diversion: 0.2,
        yieldSeconds: 150,
        samples: 8,
        chance: 1,
        story: "council-log",
        unlockPort: 3,
        council: true,
        project: "lighthouse",
        requiresStory: "arrival",
        detail: "两港一起核对铺位、供暖与值班能力，重查医院船最后的离港日志。",
      },
      {
        id: "old-observatory",
        name: "旧观测站修复",
        seconds: 300,
        diversion: 0.3,
        yieldSeconds: 210,
        samples: 10,
        chance: 1,
        story: "tide-record",
        unlockPort: 3,
        council: true,
        project: "lighthouse",
        requiresStory: "council-log",
        requiresPortFocus: true,
        research: "navigation",
        equipment: { id: "scanner", level: 2 },
        detail:
          "用苇留下的多年光照记录修补观测空白，验证静潮中实际可通行的窗口。",
      },
      {
        id: "shared-watch",
        name: "分段接续演练",
        seconds: 330,
        diversion: 0.35,
        yieldSeconds: 250,
        samples: 12,
        chance: 1,
        story: "handoff-plan",
        unlockPort: 3,
        council: true,
        project: "lighthouse",
        requiresStory: "tide-record",
        requiresPortFocus: true,
        equipment: { id: "nav", level: 2 },
        detail:
          "无人探针验证双向中继、备用泊位与交班规则，为三支等待的船队制定救援方案。",
      },
    ],
    EXPEDITION_PLANS: [
      {
        id: "calibrate",
        name: "校准优先",
        seconds: 0.8,
        diversion: 1.3,
        dust: 0.85,
        samples: 0,
        detail: "集中设备尽快核验坐标；航程短，分流较多，回收星尘较少。",
        report: "探针按校准方案集中往返，优先带回了可复核的坐标。",
      },
      {
        id: "supply",
        name: "补给优先",
        seconds: 1.15,
        diversion: 0.85,
        dust: 1.2,
        samples: 4,
        detail: "多跑一段补给航程；用更长等待换取更多星尘和样本。",
        report: "探针同时运送了补给，等待稍长，带回的物资也更充足。",
      },
      {
        id: "relay",
        name: "分段接续",
        seconds: 1,
        diversion: 0.65,
        dust: 1,
        samples: 2,
        detail: "分批使用现有中继；分流最少，保持生产，并带回额外样本。",
        report: "探针分段接续，两地逐站核对，航站保留了更多生产能力。",
      },
    ],
    STORIES: {
      hospital: {
        title: "最后一盏手术灯",
        text: "医院船里没有幸存者。但手术灯仍在亮着，备用电源护着一份没有发出的平安讯息。你准备带回什么？",
        choices: [
          {
            id: "scrap",
            name: "拆解船体",
            detail: "立即获得 60 秒产量的星尘。",
            dustSeconds: 60,
          },
          {
            id: "repair",
            name: "修复备用电源",
            detail: "获得永久舰装「医疗舱电源」，装备后产量 +10%。",
            module: "medbay",
          },
          {
            id: "preserve",
            name: "保留那份讯息",
            detail: "记录故事，并带回额外 3 份航站样本。",
            samples: 3,
          },
        ],
      },
      garden: {
        title: "等不到的日出",
        text: "温室的日历停在很久以前。最后一页写着：如果有人读到这里，请替我们给这株幼苗一次日出。",
        choices: [
          {
            id: "scrap",
            name: "回收光照设备",
            detail: "立即获得 90 秒产量的星尘。",
            dustSeconds: 90,
          },
          {
            id: "repair",
            name: "重新点亮温室",
            detail: "获得永久舰装「温室集光阵」，光帆产量 +30%。",
            module: "solar",
          },
          {
            id: "preserve",
            name: "带着幼苗启航",
            detail: "记录故事，并带回额外 5 份航站样本。",
            samples: 5,
          },
        ],
      },
      relay: {
        title: "终于收到的回信",
        continuity: {
          story: "hospital",
          choices: {
            scrap:
              "当年拆解医院船时登记的船体编号，替你在漂泊中继中找到了同一条航线。那些金属没有白白离开。",
            repair:
              "修复过的备用电源播出完整离港日志，你沿着其中的通信频段，找到了漂泊中继。那盏灯一直指着这里。",
            preserve:
              "你保存的平安讯息里藏着一个回执地址。如今，星港终于有能力把它送往该去的地方。",
          },
        },
        text: "迟到的回执从远方传来：『这里是灯塔九号。我母亲在那艘船上。谢谢你告诉我她最后做了什么。』回信者阿遥并不要求奇迹，只问这条航线能否再次通行。你准备怎样连接两地？",
        choices: [
          {
            id: "public",
            name: "共享中继频段",
            detail: "带回额外 6 份样本，供两地建设。",
            samples: 6,
          },
          {
            id: "power",
            name: "为通信阵列供电",
            detail: "获得储能矩阵或升 1 级；满 3 级时改为 6 份样本。",
            module: "battery",
            overflowSamples: 6,
          },
          {
            id: "salvage",
            name: "回收废弃中继外壳",
            detail: "获得 120 秒产量的星尘，保留通信核心。",
            dustSeconds: 120,
          },
        ],
      },
      nursery: {
        title: "不只是一株幼苗",
        continuity: {
          story: "garden",
          choices: {
            scrap:
              "回收光照设备时留下的序号，对应着种子库的培育清单。设备离开了旧温室，里面的记录却替更多种子找到了家。",
            repair:
              "重新点亮的温室送来一份发芽记录。失重种子库据此确认：这条航线还有人照顾生命。",
            preserve:
              "你带走的幼苗已经长出新叶。叶片的纹路与种子库的标本一致，它曾经属于一整座尚未醒来的花园。",
          },
        },
        text: "库门后不是燃料，而是数千个休眠的种子盒。园艺员苇的录音说：『别把我的名字刻在墙上。种下它们，等别人来坐一坐。』阿遥发来消息，她的航站能出人手，却缺少可种植的土地。你选择先带回什么？",
        choices: [
          {
            id: "seeds",
            name: "带回种子与培育记录",
            detail: "带回额外 8 份样本，准备永久育种舱。",
            samples: 8,
          },
          {
            id: "light",
            name: "接续旧库的光照阵列",
            detail: "获得温室集光阵或升 1 级；满 3 级时改为 8 份样本。",
            module: "solar",
            overflowSamples: 8,
          },
          {
            id: "tools",
            name: "回收闲置培育机械",
            detail: "获得 150 秒产量的星尘，种子留在恒温箱中。",
            dustSeconds: 150,
          },
        ],
      },
      horizon: {
        title: "有人点亮另一端",
        text: "黎明边界没有宝藏船，只有一座靠轮流停机维持的航站。阿遥站在观测窗前：『你不是来取走最后一点东西的，对吗？』你把星港、种子库和中继的坐标交给她。第一次，屏幕上的航线不再以残骸为终点。远航灯塔需要一份启用宣言。",
        choices: [
          {
            id: "welcome",
            name: "先向漂泊者发出邀请",
            detail: "带回额外 10 份样本，为接待来船做准备。",
            samples: 10,
          },
          {
            id: "archive",
            name: "先校验每一段安全航线",
            detail: "获得惯性导航仪或升 1 级；满 3 级时改为 6 份样本。",
            module: "nav",
            overflowSamples: 6,
          },
          {
            id: "supply",
            name: "先送出一批建设物资",
            detail: "获得 180 秒产量的星尘，完成两地共同回收。",
            dustSeconds: 180,
          },
        ],
      },
      observations: {
        title: "两份互相矛盾的坐标",
        text: "白噪声海里，导航仪和中继读出的位置相差一个航段。祁岳拿出一张补给队的合影：『十一年前，我们相信了一座失准的信标。我的搭档没能回来。』你让无人探针往返三次，留下原始记录。归航确认：这里可以短程通行，但旧坐标不能继续使用。祁岳把自己保存的观测交给你：『先证明每一段都能回来。』",
        continuity: {
          story: "horizon",
          choices: {
            welcome:
              "阿遥记得你向漂泊者发出的邀请。她说，邀请需要一条真正能走的航路。",
            archive: "你先校验安全航线的决定，让祁岳愿意公开旧观测。",
            supply: "你送来的建设物资已经装进探针；两地一起承担这次核验。",
          },
        },
        choices: [
          {
            id: "share",
            name: "公开两地的观测",
            detail: "额外 6 份样本；共同保留可复核的数据。",
            samples: 6,
          },
          {
            id: "verify",
            name: "制作独立校验仪",
            detail: "惯性导航仪升 1 级；满级转为 6 份样本。",
            module: "nav",
            overflowSamples: 6,
          },
          {
            id: "recover",
            name: "回收失准的旧设备",
            detail: "额外获得 150 秒产量的星尘，并保存拆检记录。",
            dustSeconds: 150,
          },
        ],
      },
      beacon: {
        title: "你们能听见吗？",
        text: "旧信标一直广播错误的入口坐标，求助频道却留下了最近的声音。『我们换了三次频率。你们能听见吗？』失联船队没有冲进错误入口，而是停在安全阴影区等待。阿遥握住话筒：『听见了。先留在那里，我们会给出能核验的路线。』你已经找到偏移来源，现在决定交接前先做什么。三种安排都保留安全等待位置。",
        continuity: {
          story: "observations",
          choices: {
            share: "两地公开的观测让船长可以自己核对入口。",
            verify: "独立校验仪辨认出了信标的固定偏移。",
            recover: "拆检旧设备留下的记录，指出了失准的频段。",
          },
        },
        choices: [
          {
            id: "calibrate",
            name: "先校准旧信标",
            detail: "残骸透镜升 1 级；满级转为 6 份样本。",
            module: "scanner",
            overflowSamples: 6,
          },
          {
            id: "aid",
            name: "先送应急供给",
            detail: "额外 8 份样本；船队可以安心等待下一段交接。",
            samples: 8,
          },
          {
            id: "depot",
            name: "先设无人补给点",
            detail: "额外获得 180 秒产量的星尘，留下可交接的补给记录。",
            dustSeconds: 180,
          },
        ],
      },
      arrival: {
        title: "第一支船队，已经进港",
        text: "船队沿着验证过的短航段依次靠港，最后一艘船也完成了人数核对。舱门里带来的有粮食、工具，还有写给园丁苇的信。阿遥把信带到育种舱：『我们替他种下。等下一批孩子来，在树荫下读。』祁岳检查交接记录：『下次谁来接班？』阿遥举起值班表：『先从我的班开始。』船长提醒你，远处的静电正出现十一年前静潮的纹路。归航开始核对旧守灯协议；这一支船队已经安全，你们可以慢慢准备下一步。",
        continuity: {
          story: "beacon",
          choices: {
            calibrate: "校准后的信标给出了第一段可靠的入口坐标。",
            aid: "收到应急供给的船员有了余力，亲自参与逐段核验。",
            depot: "无人补给点成为两地交班的第一个固定位置。",
          },
        },
        choices: [
          {
            id: "watch",
            name: "共同签下值班表",
            detail: "额外 10 份样本；记录两地交接，开放永久两港补给线。",
            samples: 10,
          },
          {
            id: "letters",
            name: "先把信带到育种舱",
            detail:
              "温室集光阵升 1 级；满级转为 8 份样本。开放永久两港补给线。",
            module: "solar",
            overflowSamples: 8,
          },
          {
            id: "unload",
            name: "一起卸下建设物资",
            detail: "额外获得 210 秒产量的星尘。开放永久两港补给线。",
            dustSeconds: 210,
          },
        ],
      },
    },
    COUNCIL_STORIES: {
      "council-log": {
        title: "我们今天还能接住谁",
        continuity: {
          story: "arrival",
          choices: {
            watch: "阿遥把第一班值守的名单带到会议上，先问下一班谁来接替。",
            letters:
              "你读给新树的信留在育种舱。新来的居民也愿意为下一支船队留一个地址。",
            unload:
              "第一支船队带来的工具已经入库，祁岳据此重算了扩建和供暖能力。",
          },
        },
        text: "守灯协议把三支等待的船队列为『无法确认接待』。你问归航，这一栏的人应该把船开到哪里，屏幕没有地址。祁岳认真核对铺位、供暖与轮班人数；阿遥把两港的求助频道接进会议室。医院船日志记着十一年前最后一次广播：旧泊位关闭，等待下一次认证窗口。那个窗口没有再来。禾继续照顾伤员，把平安讯息留在备用电源里。阿遥在育种舱坐了一会儿，回来后说：『我希望那时有人接住她。但我不能要求你改写那一天。我想知道的是，我们今天还能接住谁。』两港同意先把建设重点做成实际安排。三支船队仍在安全泊位等待，下一步由你准备。",
        choices: [
          {
            id: "capacity",
            name: "公开接待与轮班清单",
            detail: "额外 6 份样本。开放三种永久建设方向。",
            samples: 6,
          },
          {
            id: "listen",
            name: "先记录每支船队的需要",
            detail: "额外 6 份样本。开放三种永久建设方向。",
            samples: 6,
          },
          {
            id: "source",
            name: "保存原始离港记录",
            detail: "额外 6 份样本。开放三种永久建设方向。",
            samples: 6,
          },
        ],
      },
      "tide-record": {
        title: "有些窗口会再打开",
        continuity: {
          story: "council-log",
          choices: {
            capacity: "两港公开的清单，给每次观测留出了可以接班的人手。",
            listen:
              "等待船队的需求记录提醒大家：确认窗口时，也要确认到达后的补给。",
            source: "保存原始记录的做法，让这次观测仍能追溯每个数据来源。",
          },
        },
        text: "旧观测站失去了数年的航路记录，苇的育种档案却每天记下光照变化。植物经历过的明暗补齐了观测空白。归航核对两份原始资料，发现静潮由多组周期叠加而成；旧网只保存灾难后的短期记录，把所有失联航段标成永久不可用。有些窗口会短暂重开，有些依然不能通过。你们让探针实际往返，只把已经验证的窗口交给船长，并为每段航路标出观察员、交接点和备用泊位。祁岳说：『记录能让别人复核，我才敢交给下一班。』苇留下的是旧录音与植物，新的核验由仍在这里的人完成。",
        choices: [
          {
            id: "crosscheck",
            name: "让两港独立复核",
            detail: "额外 8 份样本。开放分段接续演练。",
            samples: 8,
          },
          {
            id: "light-record",
            name: "保留植物与光照原始记录",
            detail: "温室集光阵升 1 级；满级转为 8 份样本。",
            module: "solar",
            overflowSamples: 8,
          },
          {
            id: "fallback",
            name: "先标出安全等待泊位",
            detail: "额外获得 180 秒产量的星尘。开放分段接续演练。",
            dustSeconds: 180,
          },
        ],
      },
      "handoff-plan": {
        title: "把承诺交给下一班",
        continuity: {
          story: "tide-record",
          choices: {
            crosscheck: "两港的独立复核都已经签名；任何一方都可以提出暂停。",
            "light-record":
              "光照与植物记录留在观测台旁，新来的园艺工也能读懂它们。",
            fallback: "备用泊位先写进交接表，探针每到一站都确认可以安全等待。",
          },
        },
        text: "探针按双向中继逐段往返，在每个交接点先确认观察结果、接班人和备用泊位。归航核验了整套方案：中央保存原始记录并发出警告，现场负责核对自己能看见的航段，任何一站都能暂停。祁岳要求出发前说明谁承担风险、谁来接班、什么情况停止，然后把自己的名字写进第一班名单。阿遥把名单读给等待的船长：『每一段我们都会重新确认。需要停下时，就在已经核验的泊位等。』旧守灯协议仍在运行，但两港已经备好一份可执行、可复核的替代方案。三支船队的正式救援将在第五章开始；现在的等待没有离线惩罚。",
        choices: [
          {
            id: "joint-watch",
            name: "共同签署第一班名单",
            detail: "额外 10 份样本。第四章完成，轮班安排永久归档。",
            samples: 10,
          },
          {
            id: "public-record",
            name: "把交接与暂停条件公开",
            detail: "惯性导航仪升 1 级；满级转为 8 份样本。第四章完成。",
            module: "nav",
            overflowSamples: 8,
          },
          {
            id: "backup",
            name: "再次核对备用泊位",
            detail: "额外获得 210 秒产量的星尘。第四章完成。",
            dustSeconds: 210,
          },
        ],
      },
    },
    CHARACTERS: [
      {
        id: "ayao",
        name: "阿遥",
        role: "灯塔九号通信员",
        story: "relay",
        text: "她收到了母亲禾留下的记录。医院船里没有幸存者；她把那份记忆带到仍然活着的人身边。",
      },
      {
        id: "wei",
        name: "苇",
        role: "已故园丁 · 录音与来信",
        story: "nursery",
        text: "他留下的种子重新发芽。档案中的话来自旧录音，新的来信由两地居民代为收藏。",
      },
      {
        id: "qiyue",
        name: "祁岳",
        role: "灯塔九号维护负责人",
        story: "observations",
        text: "曾因错误信标失去搭档。他需要可复核的航路，也愿意把经验教给能接班的人。",
      },
      {
        id: "home",
        name: "归航",
        role: "归航星港调度程序",
        story: "beacon",
        text: "旧认证曾让它关闭陌生入口。新的观测与交接记录，正成为它学习判断的依据。",
      },
    ],
    LETTERS: [
      {
        id: "today",
        from: "ayao",
        story: "council-log",
        title: "今天还能接住的人",
        text: "母亲的最后一天已经记在原始日志里。我把那份讯息交给档案，今天的值班名单交给还活着的人。我会接下一班，也会确认有人接我的班。——阿遥",
      },
      {
        id: "light-years",
        from: "wei",
        story: "tide-record",
        title: "多年光照记录",
        text: "第 412 次光照校正：幼苗在长时间阴影后仍能发新叶。原始时段见附表。——苇，旧育种记录。附注：两港观测员已用实际往返验证对应航段，植物记录作为复核资料保存。",
      },
      {
        id: "next-watch",
        from: "qiyue",
        story: "handoff-plan",
        title: "谁来接我的班",
        text: "出发前写清观察员、接班人和暂停条件。我已经签了第一班；下一班也签过以后，我们再把路线交出去。备用泊位始终保留，等待不算失败。——祁岳",
      },
      {
        id: "receipt",
        from: "ayao",
        story: "relay",
        title: "回执已经收到",
        text: "给归航星港：母亲的记录已经收好。我们隔着很长的静电说过话，如今终于可以留下回信的地址。——阿遥",
        continuity: {
          story: "hospital",
          choices: {
            scrap: "你保留的拆解登记，让我们认出了船体编号。",
            repair: "备用电源留下了母亲最后工作的离港日志。",
            preserve: "那份没有发出的平安讯息，如今终于有了收件人。",
          },
        },
      },
      {
        id: "shade",
        from: "wei",
        story: "nursery",
        title: "留给树荫的录音",
        text: "别把我的名字刻在墙上。种下它们，等别人来坐一坐。——苇，旧育种记录",
        continuity: {
          story: "garden",
          choices: {
            scrap: "旧设备回收清单里，仍能查到这一批种子的来处。",
            repair: "你修复的集光阵，给幼苗留下了第一束稳定的光。",
            preserve: "你带回的幼苗，如今已经有了同伴。",
          },
        },
      },
      {
        id: "handoff",
        from: "qiyue",
        story: "observations",
        title: "我的那一份观测",
        text: "我一直留着那张合影。验证航线不会把失去的人带回来，但会让下一班人知道怎么回家。这份原始记录交给你，也请交给接你班的人。——祁岳",
      },
      {
        id: "proof",
        from: "home",
        story: "beacon",
        title: "新的判断依据",
        text: "归档：旧信标坐标失效。新入口包含独立观测、等待位置、求助频段。来船尚未登记，不等于来船没有求助。需要继续核对守灯协议。——归航",
      },
      {
        id: "first-watch",
        from: "ayao",
        story: "arrival",
        title: "第一班值守",
        text: "今天最后一艘船也靠港了。孩子们问，园丁会不会收到那些信。我说，我们把信读给新长的树。下一班我来守频道，你可以去休息。——阿遥",
      },
    ],
    PROJECTS: [
      {
        id: "relay",
        name: "共鸣中继",
        mission: "message",
        story: "relay",
        cores: 2,
        samples: 10,
        detail: "永久全舰队产量 ×1.05；开放失重种子库。",
        text: "共鸣中继接通。阿遥的声音第一次不再隔着长久的静电：『收到，归航星港。』",
      },
      {
        id: "nursery",
        name: "永久育种舱",
        mission: "seedbank",
        story: "nursery",
        cores: 3,
        samples: 14,
        detail: "每次成功探索永久多带回 1 份样本；开放黎明边界。",
        text: "第一批种子在育种舱里苏醒。这里开始生产的，除了星尘，还有下一个春天。",
      },
      {
        id: "lighthouse",
        name: "远航灯塔",
        mission: "horizon",
        story: "horizon",
        cores: 4,
        samples: 20,
        detail: "所有探索时间永久缩短 10%；第二章完成。",
        text: "远航灯塔亮起，另一端也传来回应。那些曾只属于一个人的归航坐标，成为了两座航站之间的路。第二章「远航星图」完成。",
      },
    ],
    PORT: [
      {
        name: "重新点亮通信塔",
        cores: 2,
        samples: 4,
        text: "第一束光离开了寂静航站。远处传来温室的坐标：航线还没有结束。",
      },
      {
        name: "修复跃迁泊位",
        cores: 5,
        samples: 8,
        text: "旧泊位接上了新的电源。船不再只是路过，这里终于可以成为归航的地方。",
      },
      {
        name: "建成归航星港",
        cores: 9,
        samples: 12,
        text: "最后一盏灯亮起。医院船的讯息、温室的幼苗和拾荒者们，都有了回来的地址。",
      },
    ],
    CAPABILITIES: [
      {
        run: 1,
        id: "autoBuy",
        name: "自动购买",
        detail: "每秒按产量回本时间购买，首艘无人机随新航次启航。",
      },
      {
        run: 2,
        id: "planning",
        name: "预算与优先级",
        detail: "可设置保留星尘，并选择均衡、里程碑或高级设施优先。",
      },
      {
        run: 3,
        id: "autoResearch",
        name: "自动研究",
        detail: "每 5 秒研究一项可负担科技，同样遵守预算。",
      },
      {
        run: 4,
        id: "autoDispatch",
        name: "重复派遣",
        detail: "自动收取普通报告并继续安全探索，故事选择由你处理。",
      },
    ],
  };
  data.MISSIONS.push(...data.COUNCIL_MISSIONS);
  Object.assign(data.STORIES, data.COUNCIL_STORIES);
  return Object.freeze(data);
});
